feat: changed padding to scale
iamhectorsosa/screenshot pull request #63
Opened 2023-05-22 13:09 UTC by alefDev-prog

fixes #57

What I have done:

1. Renamed variables, functions, types and so on from "padding" to "scale"
2. Set a constant padding of 4% to the parent-element of `ClipBoardImage` in _page.tsx_
3. In _ClipBoardImage.tsx_ adapted the slider and input
4. In the `Image` element, within its `style`, added a scale css-property

2023-05-22 13:52 UTC, ekqt requested changes
Good work on the implementation. Here are a couple of needs that we would still need:

- Could we go ahead and control the [overflow](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow) of the image and hide it. The image should never be outside of the frame itself.
- Could we add two controls for x and y transformation. We can rename the label as Scale and Transformation and place the sliders below.
- Each slider should have plus and negative values from -50 to 50 perhaps? Give it a shot and see what works best. The default should be at 0 and the slider should be in the middle of its length.
- Grab inspo from the sliders that are already in place here

![image](https://github.com/ekqt/screenshot/assets/77650775/5abee5f1-3ee5-4f2a-a605-1386563cee6e)

2023-05-22 13:52 UTC, ekqt commented on src/app/page.tsx
> +                    padding: `4%`,
Can we replace this for a TailwindCSS class if it will be fixed? `p-[4%]` I would still like to preserve percentage. See if it's possible.

2023-05-23 13:50 UTC, alefDev-prog commented
Hi, I have now fixed the things you wanted to change

2023-05-23 14:19 UTC, ekqt commented on src/app/page.tsx
> +                    overflow:"hidden"
This could be a utility class: `overflow-hidden`

2023-05-23 15:09 UTC, alefDev-prog commented
Hello again @ekqt, I have now added the number inputs. I have made them wider so that the minus sign can fit, if it displays "-100".  However, as the input is of type number and it has an onChange attribute, you can't write negative numbers in them. Do you have an idea on how to solve this?

2023-05-23 16:20 UTC, ekqt approved these changes
In HTML, the number input type is designed to accept only non-negative numeric values by default. I'm afraid we cannot change this. But the implementation is really good. The number value is an aid more than anything else. Great job!

2023-05-24 07:44 UTC, merged

2023-05-24 15:06 UTC, iamhectorsosa commented
I refactored the settings components today (they changed a bit bit), wanted to organize and help further development. I'm pretty happy with how the scale and position feature works! Just wanted to stop by again and thank you again for the good job!

![image](https://github.com/iamhectorsosa/screenshot/assets/77650775/122814d8-9ee6-4c3a-87fd-c7b42cd5d3cd)

2023-05-24 17:18 UTC, alefDev-prog commented
You're welcome, I enjoyed working on it. I like the adjustments you did!